name: net

services:
  cloudflared:
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    environment:
      - UPSTREAM1=https://1.1.1.1/dns-query
      - UPSTREAM2=https://1.0.0.1/dns-query
      - PORT=5054
      - ADDRESS=0.0.0.0
      - METRICS=127.0.0.1:8088
    network_mode: host

  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    depends_on:
      - cloudflared
    environment:
      - TZ=America/Sao_Paulo
      - FTLCONF_webserver_api_password=#etc92*oi!
      - FTLCONF_dns_upstreams=127.0.0.1#5054
      - FTLCONF_webserver_port=8053
      - DNSMASQ_USER=pihole
    volumes:
      - /home/docker/dnsmasq.d:/etc/dnsmasq.d
      - /home/docker/pihole:/etc/pihole
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_NICE
